name: 📦 Release CLI

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '18'

    - name: Build distZip
      working-directory: sample-app
      run: ./gradlew :cli:distZip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload CLI ZIP
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cli/build/distributions/grw-cli.zip
        asset_name: grw-cli.zip
        asset_content_type: application/zip
